version: 0.0
os: linux
files:
  - source: /target/SampleMavenTomcatApp.war
    destination: /tmp/codedeploy-deployment-staging-area/
  - source: /scripts/configure_http_port.xsl
    destination: /tmp/codedeploy-deployment-staging-area/
hooks:
  ApplicationStart:
    - location: scripts/start_application
      timeout: 300
